-- MySQL Script generated by MySQL Workbench
-- 06/27/15 13:31:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TaNaMesa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TaNaMesa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TaNaMesa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `TaNaMesa` ;

-- -----------------------------------------------------
-- Table `TaNaMesa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaNaMesa`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(100) NOT NULL,
  `sobreNomeUsuario` VARCHAR(200) NOT NULL,
  `loginUsuario` VARCHAR(100) NOT NULL,
  `senhaUsuario` VARCHAR(100) NOT NULL,
  `emailUsuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaNaMesa`.`Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaNaMesa`.`Receita` (
  `idReceita` INT NOT NULL,
  `nomeReceita` VARCHAR(100) NOT NULL,
  `descricaoReceita` LONGTEXT NULL,
  `dificuldadeReceita` VARCHAR(10) NULL,
  `publicaReceita` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idReceita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaNaMesa`.`PassoReceita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaNaMesa`.`PassoReceita` (
  `idPassoReceita` INT NOT NULL,
  `fkReceita` INT NOT NULL,
  `seqPasso` INT NOT NULL,
  `tipoPasso` TINYINT(1) NOT NULL,
  `tempoPasso` TIME(0) NULL,
  `descricaoPasso` LONGTEXT NULL,
  PRIMARY KEY (`idPassoReceita`, `fkReceita`),
  INDEX `fk_PassosReceita_Receita_idx` (`fkReceita` ASC),
  CONSTRAINT `fk_PassosReceita_Receita`
    FOREIGN KEY (`fkReceita`)
    REFERENCES `TaNaMesa`.`Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaNaMesa`.`Igrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaNaMesa`.`Igrediente` (
  `idIgrediente` INT NOT NULL,
  `fkReceita` INT NOT NULL,
  `nomeIgrediente` VARCHAR(100) NOT NULL,
  `seqIgrediente` INT NOT NULL,
  `medidaIgrediente` VARCHAR(20) NOT NULL,
  `qtdIgrediente` DECIMAL NOT NULL,
  PRIMARY KEY (`idIgrediente`, `fkReceita`),
  INDEX `fk_Igrediente_Receita1_idx` (`fkReceita` ASC),
  CONSTRAINT `fk_Igrediente_Receita1`
    FOREIGN KEY (`fkReceita`)
    REFERENCES `TaNaMesa`.`Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
